### ISSUE TITLE
Emails to ci-alert@iojs.org are rejected since November 24th

### ISSUE THREAD

**Issue by Starefossen** [nodejs/email#10]
Currently investigating an issue where emails sent to `ci-alert@iojs.org` from [jenkins-monitor](https://github.com/Starefossen/jenkins-monitor) via [SendGrid](https://sendgrid.com/) gets rejected.

```
EMAIL: ci-alert@iojs.org
REASON: 550 5.1.0 Recipient rejected: <ci-alert@iojs.org>
SMTP-ID: <uiKU_c9ITDaEk4-ku4EfWw@ismtpd0002p1lon1.sendgrid.net>
PROCESSED STRING: November 26, 2015 - 04:00:06
AMMSGID: uiKU_c9ITDaEk4-ku4EfWw.filter0019p1las1.10896.5656D8223D.0
```

---

<img width="521" alt="screen shot 2015-11-26 at 14 10 36" src="https://cloud.githubusercontent.com/assets/968267/11423804/ed3217b0-9447-11e5-893a-b2c53c4516c5.png">

**Comment by jbergstroem** [comment]
(Can confirm this)

**Comment by rvagg** [comment]
wow, this is a bit of a screwup on my end, see fix @ https://github.com/nodejs/email/commit/9c992cee5e9549c0f6c9a4c67df17b36d8f46a24
basically I'd turned most of the routes into requiring the addresses to be `foo@iojs.org/`
