### ISSUE TITLE
PSA: limiting ability to merge to @build-infra to reduce chances of oversight

### ISSUE THREAD

**Issue by refack** [nodejs/email#135]
Currently this repo does not have auto-deploy mechanics. Deployment can be done only by a member of @nodejs/build-infra.
To reduce chances of oversight and confusion about when a change takes effect, only infra members should merge code, and by that confirm that the change was deployed.

**Comment by rvagg** [comment]
how about you put that in the README @refack?

**Comment by refack** [comment]
PR opened https://github.com/nodejs/email/pull/136
