### ISSUE TITLE
unnecessary aliases?

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/email#14]
Just wondering why we have some of these personal ones?

- `{ "from": "rvagg", "to": "rod@vagg.org" }`
- `{ "from": "jbergstroem", "to": "bugs@bergstroem.nu" }`

Also what are these used for? They appear as though they could be the same?

```json
  { "from": "admin", "to": [
    "rod@vagg.org"
  ] },
  { "from": "accounts", "to": [
    "rod@vagg.org"
  ] },
```

cc @rvagg and @jbergstroem I guess?

**Comment by rvagg** [comment]
The first two are testing, they are only on @iojs.org, not @nodejs.org (which itself has a bunch of historical personal addresses). The second two are intended to expand to include other people. accounts@ is what I've been using to sign up the foundation to various services, I don't recall what I thought admin@ would be but I can't recall if it's in use anywhere (perhaps it's for one of those services that require you to have a certain address on a domain to verify ownership ... I should have taken notes!). Either way, those two aliases should also include @jbergstroem and @orangemocha I think.

**Comment by jbergstroem** [comment]
Feel free to drop my testing/personal one.

**Comment by jbergstroem** [comment]
Lets close this; happy to delete mine if someone insists -- I don't really use it; but its a good shorthand for "is it working?:.
