### ISSUE TITLE
Accidentally committed directly to add Matteo to zoom list

### ISSUE THREAD

**Issue by mhdawson** [nodejs/email#185]
Sorry accidentally committed directly as I hit the wrong button instead of opening PR - https://github.com/nodejs/email/commit/d628d9917ddfcd9ef56a1b28509e697fde99dccd

I don't think it makes sense to revert/make new PR but opening this  as an FYI/Transparency. If I can get a few thumbs up in place of what would have been PR approvals I'll close and publish the change to make it effective.

**Comment by mcollina** [comment]
Thanks!

**Comment by mhdawson** [comment]
deployed.
