### ISSUE TITLE
Give access to NodeSchool

### ISSUE THREAD

**Issue by mikeal** [nodejs/email#35]
One of the workshoppers, `git-it`, needs to send email and is now over the free tier in the email service it uses. Would we be able to give access to the workshopper bot so that the service can continue for more Node.js users?

https://github.com/workshopper/org/issues/27#issuecomment-287199565

**Comment by jasnell** [comment]
Who is primarily responsible for the bot in case it malfunctions or becomes compromised? I would not want this is become a potential spam vector?

As long as there is reasonable assurance that the above won't be a problem, I'm +1

**Comment by mikeal** [comment]
That's a question for @jlord :)

**Comment by jlord** [comment]
✨ 

> needs to send email 

It's not actually _sending_ the email. It's _recieving_ emails from GitHub, turning them into JSON and sending it to Git-it's server. Is that something this service does?

I also may be able to eliminate this need by using Google Apps Script, which I'm looking into 🔜 .

**Comment by Trott** [comment]
I'm going to close this as stale, but if there's still lots of interest and value, please comment or re-open.
