### ISSUE TITLE
moderation mailing list

### ISSUE THREAD

**Issue by jasnell** [nodejs/email#5]
We need an email alias (perhaps `report@node.js`) that individuals can use to report CoC violations. It should forward to members of the @nodejs/inclusivity WG

@rvagg ... what is the process for getting this set up?

**Comment by TheAlphaNerd** [comment]
I know that @nebruis has a utility he built to help make it possible to use a phone call or text as well (I believe it is with twilio).

It might be good to have as an option.

**Comment by mikeal** [comment]
The state of this for `@nodejs.org` is not ideal (stuck in Google Apps managed by IT) and we aren't going to bring it to resolution by the end of the year.

IMO we should use `@iojs.org` in the meantime since Rod has proper tooling around that.

**Comment by jasnell** [comment]
Ok. That works for me.

**Comment by Starefossen** [comment]
@jasnell just make a PR against [aliases.json](https://github.com/nodejs/email/blob/master/iojs.org/aliases.json).

**Comment by mikeal** [comment]
Once this is setup on iojs.org I can ask IT to make `report@node.js` just a forward to it.

**Comment by jasnell** [comment]
hmm... the challenge with that @Starefossen is that aliases.json is public and we don't necessarily want it to be known who all is receiving the messages going to the `report` alias. There should likely be some degree of anonymity on the receiving side.

**Comment by mikeal** [comment]
Ideally the alias would just post a new issue in the moderation repo, if that is possible

**Comment by nebrius** [comment]
fwiw, here's my tool: https://github.com/nebrius/incident-reporter. It's a phone based system based on Twilio. It's more useful for live events, where response time is paramount tbh.

**Comment by rvagg** [comment]
-1 to secret lists, it's a public repo for a reason, transparency is a big deal, if someone can't list their address then I'd question their qualifications for _moderating_ anything

**Comment by rvagg** [comment]
as an aside, if a private list really was deemed necessary for some extreme reason then I imagined that it could be done with some additional tooling that pulled in data from the nodejs/secrets repo where we keep proper secret stuff

**Comment by jasnell** [comment]
The goal is not a secret mailing list, it's about providing an entry point for moderation reports. Having notes post to the moderation mailing list is a perfect solution. This is really no different than the use of security@nodejs.org as a medium for reporting sensitive security matters.

**Comment by rvagg** [comment]
and again, there's no reason for security@nodejs.org to be secret, I initially had it set up @iojs.org but it was consolidated to @nodejs.org which is unfortunately obscured behind Google Apps. I'd rather pull all of it out to a public repo, there's currently no justification for any of it being secret as far as I'm concerned.

**Comment by Starefossen** [comment]
What would have been cool is a way to link email aliases to GitHub teams:

```js
{ "from": "report", "to": [
    "@nodejs/inclusivity",
    …
  ] }
```

**Comment by bnoordhuis** [comment]
> It should forward to members of the @nodejs/inclusivity WG

The TSC should be in the loop as well.  I don't think we should offload all responsibility to a WG.

> There should likely be some degree of anonymity on the receiving side.

I disagree for similar reasons as @rvagg: transparency and accountability are important.  No shadowy cabals.

**Comment by jasnell** [comment]
At this point, I agree. The list of moderators should be absolutely public.

**Comment by jasnell** [comment]
https://github.com/nodejs/email/pull/6

**Comment by juliepagano** [comment]
For reference, there's some relevant discussion about level of involvement in moderation from the inclusivity WG over here.

https://github.com/nodejs/inclusivity/issues/16

**Comment by misterdjules** [comment]
I find having a public facing contact point @ `iojs.org` to be very confusing, since the project's name is Node.js and it's hosted @nodejs.org. There are still a lot of users who are confused about the state of the merge, adding more confusion to that seems like it would not help. Moreover, we have `security@nodejs.org`, so having `report@iojs.org` seems like it would be inconsistent. 

Creating a mailing-list `@nodejs.org` takes a few seconds, and can be done by anyone who's willing to take care of it.

**Comment by Fishrock123** [comment]
@misterdjules while true, there's severe technical limitations with setting up @nodejs.org emails for reasons I don't fully remember..

**Comment by jasnell** [comment]
We need to get those resolved. While I don't mind the `io.js` domain, for something like this it really ought to be `nodejs.org`

**Comment by Starefossen** [comment]
Can't we just set up `report@nodejs.org` to forward to the `report@iojs.org` mailing list?

**Comment by rvagg** [comment]
Yeah @Starefossen that's how I'd like to see it used, not that we publicise @iojs.org addresses but use it as a way of managing the lists more easily. @mikeal do you feel like filling an issue with the helpdesk to get a public "group" added for report@nodejs.org with report@iojs.org as the only member?

**Comment by mikeal** [comment]
@rvagg that should be easy, although I'm not sure if it'll be an account or a group. We basically just need a forward right?

**Comment by rvagg** [comment]
Yeah, just forward. If it's an account it's another $5/month, if it's a group it can be an account-less forward. Let them figure it out though.

**Comment by mikeal** [comment]
the email forward is setup, is the iojs.org automation working?

**Comment by rvagg** [comment]
@mikeal PR #6 wasn't merged, I've done that now and run the update so report@iojs.org _should_ be active, I'll try it out

**Comment by rvagg** [comment]
not working, I think maybe mailgun doesn't like aliases to point to aliases, will have to do some expansion

**Comment by rvagg** [comment]
working now, my bad
