### ISSUE TITLE
report@nodejs.org not working properly

### ISSUE THREAD

**Issue by mcollina** [nodejs/email#56]
In theory it should go to the TSC, but I know that some people are not receiving the emails.

**Comment by MylesBorins** [comment]
I don't think I've ever received an email to report

**Comment by targos** [comment]
I think the alias defined here is `report@iojs.org`

**Comment by mcollina** [comment]
https://github.com/nodejs/TSC/blob/master/CODE_OF_CONDUCT.md#appendix-a-the-reportnodejsorg-alias

we mention "report@nodejs.org" specifically in our CoC.

**Comment by targos** [comment]
I know, but this repo, AFAICT does not manage `@nodejs.org` addresses. I don't know who does.

**Comment by Trott** [comment]
I think lots of people were added to the TSC list but maybe a step was missed or something because they're not getting messages there. I think it's true for me, @fhinkel, @thefourtheye....

**Comment by rvagg** [comment]
@trott still true according to your tests? it looks like everything is in sync but I can dig further if need be.

**Comment by MylesBorins** [comment]
I've gotten tsc mail but still haven't gotten anything from report

**Comment by rvagg** [comment]
I have just sent separate test emails to report@nodejs.org and report@iojs.org, please let me know if you didn't get either of them @nodejs/tsc

**Comment by rvagg** [comment]
Actually, I think the problem here might be that the aliases are redirecting to aliases in the latest updates to aliases.json. I'm not sure that works and they should be expanded manually or automatically by our update program.

**Comment by rvagg** [comment]
For now I've done the full expansion and commited that change back here. It could be done in the update application in this repo so that it's expanded before being committed to mailgun but I don't have time for that right now (someone else is welcome to though). Second test email sent to both of those addresses.

**Comment by mcollina** [comment]
All working fine for me now.

**Comment by Trott** [comment]
I received four test messages total, two for report@iojs and two for report@nodejs.

**Comment by mhdawson** [comment]
Can this be closed ?
