### ISSUE TITLE
Aliases in need of more email addresses

### ISSUE THREAD

**Issue by Trott** [nodejs/email#64]
`admin` and `accounts` both go to @rvagg only. It seems like there are other people that might be appropriate to add for redundancy. @mhdawson perhaps?

`build` has only three people (@rvagg, @jbergstroem, @mhdawson). It seems like there might be reason to add more folks from @nodejs/build perhaps?

`ci` just goes to @joaocgreis. Again, maybe some other folks from @nodejs/build or @nodejs/jenkins-admins?

`ci-alert` still contains Alexis C.'s email. That should probably be removed. There's a second email on there I don't recognize offhand. That alias could probably use a review.

`release-validation-alert` is just @mhdawson. Not sure if that's new/experimental or not, but just bringing it up in case that's another option for adding some folks.

**Comment by refack** [comment]
I could help with `build` and `ci`, but ATM just in triage and follow up.

**Comment by gibfahn** [comment]
Something with definitions of what these things are for (or what groups they represent) would be really helpful. I'm happy to be in more, but I don't know what they're for.

**Comment by joaocgreis** [comment]
`build`: from the message in https://github.com/nodejs/email/commit/10349acf71bc561bf88130403e7ada1af42b811d it seems to be used for the npm user.

`ci` is the email for @nodejs-ci . We can quickly add other emails if needed for some reason, so for now it's good as is.

`ci-alert` should be updated. I also don't recognize `johphi` (perhaps one of our infra contacts at some point?). This is for notifications when workers go offline in CI, so all @nodejs/build are welcome. However, the last email I have is dated July 13, so there might be some issue with it. @Starefossen set it up, IIRC.

It would be good to have some sort of descriptions in the file or in a `README.md`.

**Comment by rvagg** [comment]
build, admin and accounts need to be restricted to the smaller build/infra team, they are used to authenticate for various infra accounts. Mostly we just use build, IIRC accounts was used really early on but I can't think of anything it's still used for. admin is one of those accounts you need to prove you own a domain, I think I may have made that one to get SSL certs but it's not used beyond that. Its special status as a "prove your ownership" is another reason it should be limited.

The changes I can suggest here are:
* Joao should be added to build, he's infra
* The admin alias should have the same users as build, I don't expect it to be useful again any time soon
* accounts can be removed, _I think_ (can add it back if we discover a reason for it!)
* The ci address doesn't need to change, it's only for the GitHub account that Joao manages, perhaps we should expand access to that GitHub account though so we have more redundancy.
* ci-alert is broken at the moment, would nice to have it fixed, perhaps we need to take over management of that bot? It used to post on IRC too. If it gets going again we could add anyone in build that wanted to. 
* release-validatiom-alert is the new downloads validator that IBM folks worked on. It could potentially be replaced with ci-alert as there's a similar group of people that could be notified.

**Comment by mhdawson** [comment]
I'm not sure that ci-alert is the right list of people for release-validation-alert.  I think only members of the release team would be able to fix up a problem where the tarballs are broken.

**Comment by mhdawson** [comment]
Answering the initial question from @Trott I had called for volunteers to be added to release-validation-alert but I don't have any yet. I was hoping it would be a good subset of the @nodejs/release team.

**Comment by joaocgreis** [comment]
> The ci address doesn't need to change, it's only for the GitHub account that Joao manages, perhaps we should expand access to that GitHub account though so we have more redundancy.

Login details are already in `secrets/build/infra/ci-iojs-org`

**Comment by Trott** [comment]
Most of the issues originally flagged in this issue have been addressed. I'm going to close this and open separate issues (or PRs where appropriate) for the remaining issues.
