### ISSUE TITLE
security alias

### ISSUE THREAD

**Issue by mikeal** [nodejs/email#7]
Can we remove the forward to security@nodejs.org and instead forward it to the current members of the security group. Then we can forward nodejs.org, rather than the other way around.

**Comment by rvagg** [comment]
@mikeal can you get the current list from the helpdesk please? I don't have a good record of who is on it.

**Comment by rvagg** [comment]
^ one of the reasons we really need to move away from relying on Google Apps gated by the LF, it's ridiculous that we don't have insight to this.

**Comment by jbergstroem** [comment]
Without travelling too far away from this; is there an issue somewhere about mx hosting for nodejs.org?

**Comment by misterdjules** [comment]
@rvagg I can make you an admin of the @nodejs.org Google Apps domain if you want to, and you'd have access to everything you need, without having to ask the LF's help desk.

**Comment by rvagg** [comment]
@jbergstroem yes it would be ideal to mx away from google apps for nodejs.org, but unfortunately google groups is already in use for it so it's not a simple exercise unfortunately.

@misterdjules can you make @mikeal an admin instead? It makes sense for him to be able to do a lot of this stuff.

**Comment by misterdjules** [comment]
@mikeal Should I make you an admin of the nodejs.org Google Apps domain?

**Comment by mikeal** [comment]
sure :)

**Comment by misterdjules** [comment]
@mikeal Sent you an invitation, you should have an email @gmail.com. I couldn't change the invitation email, hence the formal, non-sensical invitation email :)

**Comment by jbergstroem** [comment]
According to [the mailgun routes page](https://documentation.mailgun.com/api-routes.html#actions) I reckon it should be possible to route all email through mailgun and catch all things we then pass onto google apps. That way we can have the aliases we want while retaining the legacy stuff. Thoughts?

**Comment by Trott** [comment]
Is this still a thing?

**Comment by jbergstroem** [comment]
@Trott I don't believe much has changed. It would be preferable to have access to the domain but I know little of its "real" usage.

**Comment by misterdjules** [comment]
@jbergstroem 

>  It would be preferable to have access to the domain 

Do you mean the nodejs.org domain? If so, the Node.js Foundation has access to it.

**Comment by Trott** [comment]
Seems like this can be closed now that we're using HackerOne. If I'm wrong about that, please re-open.
