### ISSUE TITLE
inclusivity reporting email

### ISSUE THREAD

**Issue by ashleygwilliams** [nodejs/email#9]
hello-

i would like `inclusivity@nodejs.com` for reporting inclusivity specific incidents. thanks!

it should forward to a list that includes:
- ashley williams (ashley666ashley@gmail.com)
- julie pagano (julie.pagano@gmail.com)
- beau gunderson (beau@beaugunderson.com)
- nathan zadoks (nathan@nathan7.eu)
- bryan hughes (bryan@theoreticalideations.com)
- forrest norvell (forrest@npmjs.com)
- jona hugger (jona@jona.io)
- sakthipriyan vairamani (thechargingvolcano@gmail.com)
- rich trott (rtrott@gmail.com)
- kat marachan (node@sykosomatic.org)

**Comment by jbergstroem** [comment]
Without making this a catch 22 (was reading in the other issue that this is blocking) perhaps this should be held off until it is an official WG?

**Comment by jasnell** [comment]
how would this be used differently from the report@node.js alias used to report code of conduct violations and moderation issues? Having two aliases could be confusing so the distinction should be clear

**Comment by ashleygwilliams** [comment]
@jbergstroem: yeah that is complicated, i could use report@node.js for now but that ends up removing all our autonomy which isn't a precedent i want to set (if that makes any sense)
 
@jasnell: since the inclusivity WG would like to moderate itself (within itself), we'd like to have our own

**Comment by zkat** [comment]
as @ashleygwilliams pointed out, this is entirely within the scope of WG-level interactions. See https://github.com/nodejs/inclusivity/blob/master/meetings/2015-11-24.md#moderation-and-issue-management-in-wg---41 for our discussion at the recent meeting about moderation, and note that we didn't even discuss our interactions with moderation at the scale of the larger community

Having this alias would be one of a number of useful tools for us to be able to keep what are fairly sensitive discussions civil and healthy. :) I have no idea what our wider-community interactions would eventually be, but they would very likely have absolutely nothing to do with this particular aliases (as in, they would have their own channels)

**Comment by jasnell** [comment]
okie dokie :-) the only thing I'd want to avoid is confusing users as to which alias should be used as such confusion could cause delays in getting issues resolved.

@ashleygwilliams ... the best way to do this would be to go ahead and open a PR here that adds the new alias and distribution list.

**Comment by Fishrock123** [comment]
landed in https://github.com/nodejs/email/commit/ea9a396c2c54e3ac2ed566c536f723d4e5810e59
